/*
 * nfc_pos_transaction.h
 *
 *  Created on: Aug 10, 2013
 *      Author: jefferson
 */

#ifndef NFC_POS_TRANSACTION_H_
#define NFC_POS_TRANSACTION_H_

typedef enum{
	INCOMING_PEER_DEVICE_READY_RESPONSE = 1,
	INCOMING_TRANSACTION_ID_RECEIVED_CONFIRMATION = 2,
	INCOMING_PAYMENT_AMOUNT_RECEIVED_CONFIRMATION = 3,
	INCOMING_MERCHANT_ACCT_NUM_RECEIVED_CONFIRMATION = 4,
    INCOMING_SERVER_CONNECTION_SUCCESSFUL = 5,
    INCOMING_SERVER_CONNECTION_FAILED = 6,
    INCOMING_MERCHANT_AUTHENTICATION_SUCCESSFUL = 7,
    INCOMING_MERCHANT_AUTHENTICATION_FAILED = 8,
    INCOMING_CUSTOMER_AUTHENTICATION_SUCCESSFUL = 9,
    INCOMING_CUSTOMER_AUTHENTICATION_FAILED = 10,
    INCOMING_SUFFICIENT_FUNDS_RESULT = 11,
    INCOMING_INSUFFICIENT_FUNDS_RESULT = 12,
    INCOMING_TRANSACTION_SUCCESSFUL = 13,
    INCOMING_TRANSACTION_FAILED = 14,
    INCOMING_READY_FOR_RECEPT_REQUEST = 15,
    INCOMING_READY_FOR_BALANCE_REQUEST = 16
}nfc_pos_transaction_code_incoming_type;

typedef enum{
	OUTGOING_PEER_READY_REQUEST = 1,
	OUTGOING_TRY_AGAIN_REQUEST = 2,
	OUTGOING_READY_FOR_RECEIPT_RESPONSE = 3,
	OUTGOING_RECEIPT_RECEIVED_CONFIRMATION = 4,
	OUTGOING_RECEIPT_VALID_MESSAGE = 5,
	OUTGOING_RECEIPT_INVALID_MESSAGE = 6,
	OUTGOING_READY_FOR_BALANCE_RESPONSE = 7,
	OUTGOING_BALANCE_RECEIVED_CONFIRMATION = 8
}nfc_pos_transaction_code_outgoing_type;



#endif /* NFC_POS_TRANSACTION_H_ */
